name: passport_scanner
description: "Scan any passport to extract its information"
version: 0.0.2
homepage: https://github.com/alihusseinalissa/passport_scanner

environment:
  sdk: ^3.9.2
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  camerawesome: ^2.5.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  mrz_parser: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
